### ISSUE TITLE
Unable to import from utils

### ISSUE THREAD

**Issue by OlMi1** [senacor/Trader.AI#13]
When starting the stock_exchange.py, I get:

`Traceback (most recent call last):
  File "G:\Systempfads\Downloads\Trader.AI-master\Trader.AI-master\stock_exchange.py", line 4, in <module>
    from utils import read_stock_market_data
  File "G:\Systempfads\Downloads\Trader.AI-master\Trader.AI-master\utils.py", line 9, in <module>
    from keras.models import Sequential
  File "G:\Programs\python\lib\site-packages\keras\__init__.py", line 20, in <module>
    from . import initializers
  File "G:\Programs\python\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "G:\Programs\python\lib\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'`

Any ideas on how to fix that?

**Comment by FabiEbert** [comment]
This should be able to help you: https://stackoverflow.com/questions/61137954/attributeerror-module-tensorflow-python-keras-utils-generic-utils-has-no-attr

In the answers you can find quite a lot of different solutions on how to resolve that problem.

**Comment by OlMi1** [comment]
> This should be able to help you: https://stackoverflow.com/questions/61137954/attributeerror-module-tensorflow-python-keras-utils-generic-utils-has-no-attr
> 
> In the answers you can find quite a lot of different solutions on how to resolve that problem.

Thanks a lot for the quick help!
I already went through some of the stuff mentioned there, but installing a specific version throws errors. I think I will have to edit utils.
Isnt there a way around this?

**Comment by OlMi1** [comment]
Adding an "import tensorflow" and replacing 
`from keras.xy import xy`
with
`from tensorflow.keras.xy import xy`
did the trick.
Tip: If you import the project into the atom editor and right click the parent folder and choose "search in folder", it does the job for you. Saves tons of time.
